### ISSUE TITLE
visual模式下翻译一段选中英文输出结果不完整

### ISSUE THREAD

**Issue by lonuxli** [linghaihui/vim-youdao-translator#3]
visual模式下,选中一段英文,大约100个单词左右, 最终输出结果只有前面10个单词左右被翻译输出.在vim8.0及vim9.0均存在此问题.

**Comment by bujnlc8** [comment]
你的vim是不是不支持popup，`:echo has('textprop')` 看结果是否为1 ?

**Comment by lonuxli** [comment]
我的环境:echo has('textprop') 看结果为1, 测试版本为vim 8.2,并且我的.vimrc配置了
let g:translator_cache = 1
let g:translator_outputype = 'echo'

**Comment by bujnlc8** [comment]
我刚刚试了没有问题，能把你的那一段英文拿出来看看吗？

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/13796299/188387172-6422e3d3-4890-4aa5-8e56-aa3d1000b926.png">

**Comment by lonuxli** [comment]
任意长一点的英文我都会出现,例如我在visual模式下选择第一段,翻译结果长度很短,只有一行.

![vim-translator](https://user-images.githubusercontent.com/73353947/188428105-8830f452-ace5-4a93-99a9-d4e32360a1db.PNG)

**Comment by lonuxli** [comment]
Note that an architecture can provide more than the minimum requirement for any particular barrier, but if the architecture provides less than that, that architecture is incorrect.

**Comment by bujnlc8** [comment]
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/13796299/188429903-159d959e-a662-4b8c-adf4-e7805ace6975.png">

**Comment by bujnlc8** [comment]
我这边试了一下没有问题，百度和有道都没问题，可能是visual模式下获取文本有些问题

**Comment by bujnlc8** [comment]
有道确实有这个问题，换成百度吧

`let g:translator_channel='baidu'`

**Comment by bujnlc8** [comment]
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/13796299/188433736-552c336b-c20e-4b49-8467-e62c72f75e06.png">

应该是有道做了限制，之前还挺好用的啊

**Comment by bujnlc8** [comment]
有道渠道已修复，你试一下看看，可能需要清除一下缓存 @lonuxli

**Comment by lonuxli** [comment]
验证ok了, 感谢!!
